export const newsIcons = [
  require('../assets/images/newspaper1.png'),
  require('../assets/images/newspaper2.png'),
  require('../assets/images/newspaper3.png'),
  require('../assets/images/newspaper4.png'),
  require('../assets/images/newspaper5.png'),
  require('../assets/images/newspaper6.png'),
  require('../assets/images/newspaper7.png'),
  require('../assets/images/newspaper1.png'),
  require('../assets/images/newspaper2.png'),
  require('../assets/images/newspaper3.png'),
  require('../assets/images/newspaper4.png'),
  require('../assets/images/newspaper5.png'),
  require('../assets/images/newspaper6.png'),
  require('../assets/images/newspaper7.png'),
];
